env_key: HUGGINGFACE_API_KEY
api_key:  API_key
api_base: https://api-inference.huggingface.co
model: huggingface/together/Qwen/Qwen2.5-7B-Instruct
project: hugging-face
dataset: NGUUU
default_params:
  max_new_tokens: 128
  temperature: 0.7
extra_env:
  HF_HUB_ENABLE_HF_TRANSFER: "1"

eval_model:
  model: gpt-4o-mini
  api_key: API_key
  env: OPENAI_API_KEY 
  temperature: 0.0
  concurrency: 20

retrieve:
  path: ".chroma_sumco_300_3"
  embedding_model: "BAAI/bge-m3"
  rerank_model: "BAAI/bge-reranker-v2-m3"
  collection_name: "journal_db"
  top_k: 5